language: scala
scala:
- 2.11.4
before_install:
- openssl aes-256-cbc -K $encrypted_2a991e061d7c_key -iv $encrypted_2a991e061d7c_iv
  -in secure.tar.enc -out local.secure.tar -d
- tar xvf local.secure.tar
after_success:
- "{ sbt publishSigned; }"