language: scala
scala:
- 2.12.3
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_4b0ec63f044a_key -iv $encrypted_4b0ec63f044a_iv
  -in secure.tar.enc -out secure.tar -d
- tar xvf secure.tar
after_success:
- test $TRAVIS_BRANCH == "develop" && sbt publishSigned